require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-sequel

AllCops:
  NewCops: enable
  Exclude:
    - 'Rakefile'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Max: 18

Metrics/MethodLength:
  Max: 15

Sequel/ColumnDefault:
  Enabled: false
