require:
  - rubocop-rake
  - rubocop-sequel

plugins:
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'Rakefile'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Max: 18

Metrics/MethodLength:
  Max: 15
